name: Tests
on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unittests:
    name: Unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: src
    steps:
      - uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Tests
        run: python tests/test.py
